=== antonTroyan/EpamTasks/Task_5XML/files/candy.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="candies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name"/>
                <xs:element name="energy"/>
                <xs:element name="type"/>
                <xs:element name="ingredients"/>
                <xs:element name="value"/>
                <xs:element name="production"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="name" type="xs:string"/>
    <xs:element name="energy" type="xs:integer"/>

    <xs:element name="type">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type-name" type="xs:string"/>
                <xs:element name="have-filling" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ingredients">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="water" type="xs:integer"/>
                <xs:element name="sugar" type="xs:integer"/>
                <xs:element name="fructose" type="xs:integer"/>
                <xs:element name="chocolate-type" type="xs:integer" minOccurs="0"/>
                <xs:element name="vanillin" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="value">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="proteins" type="xs:integer"/>
                <xs:element name="fats" type="xs:integer"/>
                <xs:element name="carbohydrates" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== antonTroyan/EpamTasks/Task_5XML/files/candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="candies"
         xsi:noNamespaceSchemaLocation="candy.xsd">

    <name id="1">The cow</name>
    <energy>100</energy>
    <type>
        <type-name>Chocolate</type-name>
        <have-filling>Yes</have-filling>
    </type>
    <ingredients>
        <water>10</water>
        <sugar>15</sugar>
        <fructose>25</fructose>
        <chocolate-type>Black</chocolate-type>
        <vanillin>9</vanillin>
    </ingredients>
    <value>
        <proteins>10</proteins>
        <fats>15</fats>
        <carbohydrates>30</carbohydrates>
    </value>
    <production country="Russia">Roshen</production>

</candies>
